require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'medibound' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-bluetooth-status', :path => '../node_modules/react-native-bluetooth-status'

  pod 'react-native-encrypted-storage', :path => '../node_modules/react-native-encrypted-storage'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'mediboundTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  #use_flipper!({ 'Flipper-Folly' => '2.6' })
  #post_install do |installer|
   # flipper_post_install(installer)
  #end
end
